# Generated by Django 6.0.6 on 2026-07-03 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_ideastar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ideastar',
            unique_together=set(),
        ),
    ]
